[server]
rules_file = "KaifRules"

[game]
hostname = "Kaif Station 18+ğŸ˜ - Ğ¡Ğ¼ĞµÑˆĞ½ĞµĞµ ÑƒĞ¶Ğµ Ğ½Ğµ Ğ±ÑƒĞ´ĞµÑ‚ğŸ˜ [NO-TTS]"
desc = "ğŸŒŒ ĞšĞĞ™Ğ¤Ğ£Ğ®Ğ©Ğ˜Ğ™ ĞŸĞ Ğ˜Ğ’Ğ•Ğ¢, Ğ§Ğ•Ğ›ĞĞ’Ğ•Ğš ğŸ˜ğŸ‘½\n\nğŸ‘¨ğŸš€ Ğ¢Ñ‹ ğŸƒ Ğ·Ğ°Ğ»ĞµÑ‚ĞµĞ» ğŸš€ Ğ½Ğ° Kaif Station 18+ â€” Ñ‚ÑƒÑ‚ ğŸ› ï¸  Ğ¼Ñ‹ ğŸŒˆ Ğ½Ğµ ğŸš« Ğ¿Ğ°Ñ€Ğ¸Ğ¼ÑÑ, ğŸ® Ğ¸Ğ³Ñ€Ğ°ĞµĞ¼, ğŸ¸ ÑƒĞ³Ğ°Ñ€Ğ°ĞµĞ¼ ğŸ˜œ Ğ¸ ğŸ’ Ğ´Ğ°Ğ¶Ğµ ğŸ”¨ Ğ¿ĞµÑ€ĞµĞ²Ğ¾Ğ´Ğ¸Ğ¼ ğŸ›¸ Space Station 14 ğŸŒŒ Ñ‚Ğ°Ğº, Ñ‡Ñ‚Ğ¾ ğŸ’¬ Ğ¼Ğ°Ğ¼Ğ¾Ğ½Ñ‚Ñ‹ ğŸ¦£ Ğ·Ğ°Ğ²Ğ¸Ğ´ÑƒÑÑ‚.\n\nâœ¨\n\nĞ¤Ğ¾Ñ€Ğº ğŸ’» GoobStation? âœ”ï¸ Ğ•ÑÑ‚ÑŒ! ğŸ˜‚ ĞšÑ€Ğ¸Ğ½Ğ¶? âœ”ï¸ Ğ£Ğ´Ğ²Ğ¾ĞµĞ½Ğ½Ñ‹Ğ¹! ğŸŒ® ĞšĞ°Ğ¹Ñ„? âœ”ï¸ Ğ‘Ğ•Ğ¡ĞŸĞ›ĞĞ¢ĞĞ!\n\nğŸ¥¤ ĞšĞĞ™Ğ¤ĞĞ’ĞĞ¢Ğ¬ ĞĞ• Ğ—ĞĞŸĞ Ğ•Ğ©Ğ•ĞĞ ğŸ” â€” ÑÑ‚Ğ¾ ğŸ”¥ Ğ½Ğµ Ğ¿Ñ€Ğ¾ÑÑ‚Ğ¾ âœ¨ ÑĞ»Ğ¾Ğ²Ğ°, Ğ°Ğ°Ğ° ğŸ† ÑÑ‚Ğ¸Ğ»ÑŒ ğŸŒŸ Ğ¶Ğ¸Ğ·Ğ½Ğ¸! ğŸš€\n\nğŸ’€ Ğ—Ğ°Ñ…Ğ¾Ğ´Ğ¸, ğŸŒ Ğ¿Ñ€Ğ¸ÑĞ°Ğ¶Ğ¸Ğ²Ğ°Ğ¹ÑÑ ğŸŒˆ, Ñ€Ğ°ÑÑĞ»Ğ°Ğ±Ğ»ÑĞ¹ÑÑ ğŸš€ Ğ¸ ğŸ”¥ Ğ¿Ğ¾Ğ¹Ğ¼Ğ¸, Ñ‡Ñ‚Ğ¾ ğŸŒŒ ĞºĞ°Ğ¹Ñ„ â€” ÑÑ‚Ğ¾ ğŸ• Ğ²ÑĞµ, Ñ‡Ñ‚Ğ¾ ğŸ¸ Ğ½ÑƒĞ¶Ğ½Ğ¾. ğŸ˜ˆ"
maxplayers = 40
soft_max_players = 35
role_timers = false
lobbyduration = 100

[infolinks]
discord = "https://discord.gg/jQnxNEv457"

[hub]
advertise = true
tags = "lang:ru,rp:high,region:eu_e,18+"
hub_urls = "https://hub.spacestation14.com/"

[ghost]
respawn_time = 15
respawn_max_players = 999
allow_same_character = true
allow_respawn = true

[ic]
flavor_text = true

[discord]
round_end_role = "1142813805592727623"

[net]
pvs_range = 40
